In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
df = pd.read_csv('data/eiti-summary-company-payments.csv')

In [3]:
df = df[df['country'] == "Myanmar"]

In [4]:
df.head()

,created,changed,country,iso3,year,start_date,end_date,company_name,gfs_code,gfs_description,name_of_revenue_stream,currency_code,currency_rate,value_reported,value_reported_as_USD,reporting_url
31969,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014",Petronas Carigali Myanmar Inc,1112-E1,"Ordinary taxes on income, profits and capital ...",Revenue Stream: 1112E1 [Ordinary taxes on inco...,MMK,960.5121,4.017128e+10,41822777.0,https://eiti.org/api/v1.0/organisation/31689
31970,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014",Petronas Carigali Myanmar Inc,1415-E1,Royalties,Revenue Stream: 1415E1 [Royalties] - Royalties,MMK,960.5121,1.407288e+11,146514378.0,https://eiti.org/api/v1.0/organisation/31689
31971,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014",Petronas Carigali Myanmar Inc,1415-E32,Delivered/paid to state-owned enterprise(s),Revenue Stream: 1415E32 [Delivered/paid to sta...,MMK,960.5121,6.139777e+11,639219143.0,https://eiti.org/api/v1.0/organisation/31689
31972,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014",Petronas Carigali Myanmar Inc,1415-E32,Delivered/paid to state-owned enterprise(s),Revenue Stream: 1415E32 [Delivered/paid to sta...,MMK,960.5121,1.208082e+11,125774746.0,https://eiti.org/api/v1.0/organisation/31689
31973,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014",Petronas Carigali Myanmar Inc,1415-E32,Delivered/paid to state-owned enterprise(s),Revenue Stream: 1415E32 [Delivered/paid to sta...,MMK,960.5121,4.923598e+09,5126014.0,https://eiti.org/api/v1.0/organisation/31689

## Clean data

In [5]:
df["company_name"].unique()

array(['Petronas Carigali Myanmar Inc', 'TOTAL',
       'Daewoo International Corporation', 'PTT Exploration & Production',
       'Goldpetrol Co Ltd', 'MPRL E&P Pte Ltd', 'Nippon Oil', 'UNOCAL',
       'Chinnery Assets Ltd', 'SNOG Pte Ltd', 'Eternal Mining Company Ltd',
       'Kayah State Mining Production Co. (KMPC)',
       'Myanmar Pongpipat Company Limited', 'Nobel Gold',
       'Tha Byu Mining Co., Ltd.', 'Win Myint Mo Industries Co.,Ltd.',
       'DELCO (Developers Enterepreneurs Liaison Construction Organizers Limited',
       'GPS Joint Venture Co., Ltd.', 'Ngwe Yi Pale Mining Co., Ltd',
       'Max Myanmar Manufacturing Co.,',
       'Triple A Cement International Co., Ltd',
       'Myanmar Wanbao Mining Copper', 'Myanmar Yang Tse Copper Ltd',
       'CNMC Nickel Co Ltd. (MCNICO) (Tagaung Taung Nickel project)',
       'Great Genesis Gems Co., Ltd.', 'MYANMAR IMPERIAL JADE',
       'Richest Gems Co., Ltd', 'LINN LETT WIN YADANAR GEMS',
       'EVER WINNER GEMS', 'AUNG HEIN MIN GEMS', 'Wai Aung Ka Bar',
       'Ya Zar Htar Ni', 'SHWE YWET HLWAR GEMS', 'Kyauk Sein Na Gar',
       'YADANAR YAUNG CHI GEMS', 'Jade Mountain Gems', 'THI RAW MANI GEMS',
       'Kyaik International', 'MYAT YAMON GEMS', 'WINN LEI YADANA',
       'Myanmar Si Thu', '111', 'Sein Lone Taung Tan',
       'SHINING STAR LIGHT GEMS', 'Khin Zaw Aung and Brothers',
       'Xie Family', 'Aye Yar Kyauk Sein', 'WAI FAMILY GEMS',
       'AYEYAR YANDANAR GEMS', 'A Myo Thar Kyi Pwar Toe Tat Yay',
       'SHWE WAH MYAY (MANDALAY)', 'Ya Da Nar Taung Tan',
       'NAY LA PWINT GEMS', 'TREASURE WHITE LOTUS GEMS'], dtype=object)

In [6]:
companies_info_df = pd.read_csv('data/eiti_summary_companies_cleaned.csv')

In [7]:
companies_info_df.head()

,Legal name,Identification,Company_name_cl,Identification_cl,Commodities
0,Petronas Carigali Myanmar Inc,NC,PETRONAS CARIGALI MYANMAR INC.(BRANCH OFFICE),16FC/2011-2012,Oil & Gas
1,TOTAL,24FC of 1992-1993,TOTAL E & P MYANMAR (YANGON BRANCH),24FC/1992-1993,Oil & Gas
2,Daewoo International Corporation,1 FC / 2002-2003,Posco Daewoo Corporation (Myanmar E&P Office),1FC/2002-2003,Oil & Gas
3,PTT Exploration & Production,84 FC,PTTEP International Ltd. (Yangon Branch),84FC/1995-1996,Oil & Gas
4,Goldpetrol Co Ltd,173 FC,Goldpetrol Co Ltd,173 FC,Oil & Gas

In [8]:
df = pd.merge(df, companies_info_df, left_on='company_name', right_on='Legal name')

In [9]:
df[df['Commodities'] == 'Gems & Jade']['name_of_revenue_stream'].unique()

array(['Revenue Stream: 1415E1 [Royalties] - Royalties',
       'Revenue Stream: 1415E32 [Delivered/paid to state-owned enterprise(s)] - Sale Split',
       'Revenue Stream: 1415E32 [Delivered/paid to state-owned enterprise(s)] - Emporium Fees / Sale Fees',
       'Revenue Stream: 1422E [Administrative fees for government services] - Supervision Fees',
       'Revenue Stream: 1415E5 [Other rent payments] - Other significant payments (&gt; 50,000 USD)'], dtype=object)

In [10]:
df[df['Commodities'] == 'Gems & Jade']['gfs_description'].unique()

array(['Royalties', 'Delivered/paid to state-owned enterprise(s)',
       'Administrative fees for government services', 'Other rent payments'], dtype=object)

In [11]:
df['revenue_stream_short'] = df['name_of_revenue_stream'].str.split(' - ').str[1]

In [12]:
df_gemsjade = df[df['Commodities'] == 'Gems & Jade']
df_gemsjade['type'] = 'entity'
df_gemsjade['target_type'] = ''

/Library/Python/2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Library/Python/2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [13]:
df_gemsjade.head()

,created,changed,country,iso3,year,start_date,end_date,company_name,gfs_code,gfs_description,...,value_reported_as_USD,reporting_url,Legal name,Identification,Company_name_cl,Identification_cl,Commodities,revenue_stream_short,type,target_type
76,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014","Great Genesis Gems Co., Ltd.",1415-E1,Royalties,...,4419839.0,https://eiti.org/api/v1.0/organisation/31716,"Great Genesis Gems Co., Ltd.",978/2005-2006,GREAT GENESIS GEMS COMPANY LIMITED,978/2005-2006,Gems & Jade,Royalties,entity,
77,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014","Great Genesis Gems Co., Ltd.",1415-E32,Delivered/paid to state-owned enterprise(s),...,15621836.0,https://eiti.org/api/v1.0/organisation/31716,"Great Genesis Gems Co., Ltd.",978/2005-2006,GREAT GENESIS GEMS COMPANY LIMITED,978/2005-2006,Gems & Jade,Sale Split,entity,
78,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014","Great Genesis Gems Co., Ltd.",1415-E32,Delivered/paid to state-owned enterprise(s),...,400000.0,https://eiti.org/api/v1.0/organisation/31716,"Great Genesis Gems Co., Ltd.",978/2005-2006,GREAT GENESIS GEMS COMPANY LIMITED,978/2005-2006,Gems & Jade,Emporium Fees / Sale Fees,entity,
79,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014","Great Genesis Gems Co., Ltd.",1422-E,Administrative fees for government services,...,397785.0,https://eiti.org/api/v1.0/organisation/31716,"Great Genesis Gems Co., Ltd.",978/2005-2006,GREAT GENESIS GEMS COMPANY LIMITED,978/2005-2006,Gems & Jade,Supervision Fees,entity,
80,2017-02-13T07:00:42+0000,2017-02-13T07:00:42+0000,Myanmar,MMR,2014,"Apr 1, 2013","Mar 31, 2014",MYANMAR IMPERIAL JADE,1415-E1,Royalties,...,3988599.0,https://eiti.org/api/v1.0/organisation/31717,MYANMAR IMPERIAL JADE,919 / 1996-1997,MYANMAR IMPERIAL JADE (GEMS & JEWELLERY) COMPA...,919/1996-1997,Gems & Jade,Royalties,entity,

In [14]:
company_totals = df_gemsjade.pivot_table(index=['Company_name_cl'], aggfunc='sum')['value_reported']
company_totals = company_totals.to_frame()
company_totals.rename(columns={'value_reported': 'total_payments'}, inplace=True)
company_totals.reset_index(level=0, inplace=True)
company_totals

                                      Company_name_cl  total_payments
0            (1.1.1) GEMS & JEWELLERY COMPANY LIMITED    8.420018e+09
1                  AUNG HEIN MIN GEMS COMPANY LIMITED    2.196766e+09
2                           AYAR JADE COMPANY LIMITED    7.016874e+09
3     AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED    1.083479e+09
4                          Ever Winner Gems Co., Ltd.    4.459207e+09
5                  GREAT GENESIS GEMS COMPANY LIMITED    2.001655e+10
6                       JADE MOUNTAIN COMPANY LIMITED    8.592584e+09
7   KHIN ZAW AUNG & BROTHERS GEMS AND JEWELLERY CO...    4.186186e+09
8           KYAING INTERNATIONAL GEMS COMPANY LIMITED    5.351262e+09
9            KYAUK SEINN NAGAR (GEMS) COMPANY LIMITED    9.122210e+09
10         LINN LETT WIN YADANAR GEMS COMPANY LIMITED    8.079841e+09
11  MYANMAR IMPERIAL JADE (GEMS & JEWELLERY) COMPA...    4.175896e+09
12                                     Myanmar Si Thu    8.142193e+09
13                            Myat Yamon Gems Co.,Ltd    5.778486e+09
14           NATIONAL PROSPERITY GEMS COMPANY LIMITED    1.453792e+09
15                  NAY LA PWINT GEMS COMPANY LIMITED    4.575571e+09
16                       RICHEST GEMS COMPANY LIMITED    1.604481e+10
17                       Sein Lom Taung Tan Gems Ltd.    8.686355e+09
18      Shining Star Light Gems & Jewellery Co., Ltd.    9.559135e+09
19             Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.    1.188666e+09
20                     Shwe Ywet Hlwar Gems Co.,.Ltd.    2.083837e+09
21      THI RAW MANI GEMS & JEWELLERY COMPANY LIMITED    1.158135e+10
22          TREASURE WHITE LOTUS GEMS COMPANY LIMITED    1.007072e+09
23                WAI AUNG GABAR GEMS COMPANY LIMITED    1.807804e+10
24                    WAI FAMILY GEMS COMPANY LIMITED    1.109455e+09
25                   WINN LEI YADANAR COMPANY LIMITED    2.341319e+09
26                         XIE FAMILY COMPANY LIMITED    6.365315e+09
27            YADANAR TAUNG TANN GEMS COMPANY LIMITED    7.136626e+09
28            YANDANAR YAUNG CHI GEMS COMPANY LIMITED    1.893933e+09
29                YAR ZA HTAR NE GEMS COMPANY LIMITED    1.279908e+10

In [15]:
df_gemsjade = pd.merge(df_gemsjade, company_totals, on='Company_name_cl')
df_gemsjade = df_gemsjade.sort_values(by=['total_payments'], ascending=False)

In [16]:
append_dict_others = [{'Company_name_cl': 'Companies not in EITI Reconciliation', 'type': 'entity', 
                       'revenue_stream_short': 'Royalties', 'value_reported': 111092756522 },
                      
                     {'Company_name_cl': 'Companies not in EITI Reconciliation', 'type': 'entity', 
                       'revenue_stream_short': 'Sale Split', 'value_reported': 51742994736 },
                      
                     {'Company_name_cl': 'Companies not in EITI Reconciliation', 'type': 'entity', 
                       'revenue_stream_short': 'Emporium Fees / Sale Fees', 'value_reported': 11401644588 },
                      
                     {'Company_name_cl': 'Companies not in EITI Reconciliation', 'type': 'entity', 
                       'revenue_stream_short': 'Supervision Fees', 'value_reported': 1246890624 },
                      
                     {'Company_name_cl': 'Companies not in EITI Reconciliation', 'type': 'entity', 
                       'revenue_stream_short': 'Other significant payments', 'value_reported': 2186525820 }]

others_df = pd.DataFrame(append_dict_others)
others_df['total_payments'] = others_df['value_reported']
df_gemsjade = pd.concat([df_gemsjade, others_df])
df_gemsjade.tail(10)

,Commodities,Company_name_cl,Identification,Identification_cl,Legal name,changed,company_name,country,created,currency_code,...,name_of_revenue_stream,reporting_url,revenue_stream_short,start_date,target_type,total_payments,type,value_reported,value_reported_as_USD,year
86,Gems & Jade,WAI FAMILY GEMS COMPANY LIMITED,174 / 2000-2001,174/2000-2001,WAI FAMILY GEMS,2017-02-13T07:00:42+0000,WAI FAMILY GEMS,Myanmar,2017-02-13T07:00:42+0000,MMK,...,Revenue Stream: 1415E32 [Delivered/paid to sta...,https://eiti.org/api/v1.0/organisation/31739,Emporium Fees / Sale Fees,"Apr 1, 2013",,1.109455e+09,entity,9.701789e+07,101006.0,2014.0
88,Gems & Jade,AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED,1532 /1996-1997,1532/1996-1997,AYEYAR YANDANAR GEMS,2017-02-13T07:00:42+0000,AYEYAR YANDANAR GEMS,Myanmar,2017-02-13T07:00:42+0000,MMK,...,Revenue Stream: 1415E32 [Delivered/paid to sta...,https://eiti.org/api/v1.0/organisation/31740,Emporium Fees / Sale Fees,"Apr 1, 2013",,1.083479e+09,entity,8.946155e+07,93139.0,2014.0
87,Gems & Jade,AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED,1532 /1996-1997,1532/1996-1997,AYEYAR YANDANAR GEMS,2017-02-13T07:00:42+0000,AYEYAR YANDANAR GEMS,Myanmar,2017-02-13T07:00:42+0000,MMK,...,Revenue Stream: 1415E1 [Royalties] - Royalties,https://eiti.org/api/v1.0/organisation/31740,Royalties,"Apr 1, 2013",,1.083479e+09,entity,9.940174e+08,1034883.0,2014.0
105,Gems & Jade,TREASURE WHITE LOTUS GEMS COMPANY LIMITED,273/2003-2004,273/2003-2004,TREASURE WHITE LOTUS GEMS,2017-02-13T07:00:42+0000,TREASURE WHITE LOTUS GEMS,Myanmar,2017-02-13T07:00:42+0000,MMK,...,Revenue Stream: 1415E1 [Royalties] - Royalties,https://eiti.org/api/v1.0/organisation/31745,Royalties,"Apr 1, 2013",,1.007072e+09,entity,9.234732e+08,961438.0,2014.0
106,Gems & Jade,TREASURE WHITE LOTUS GEMS COMPANY LIMITED,273/2003-2004,273/2003-2004,TREASURE WHITE LOTUS GEMS,2017-02-13T07:00:42+0000,TREASURE WHITE LOTUS GEMS,Myanmar,2017-02-13T07:00:42+0000,MMK,...,Revenue Stream: 1415E32 [Delivered/paid to sta...,https://eiti.org/api/v1.0/organisation/31745,Emporium Fees / Sale Fees,"Apr 1, 2013",,1.007072e+09,entity,8.359920e+07,87036.0,2014.0
0,NaN,Others (Not in Reconciliation Scope),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Royalties,NaN,NaN,1.110928e+11,entity,1.110928e+11,NaN,NaN
1,NaN,Others (Not in Reconciliation Scope),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sale Split,NaN,NaN,5.174299e+10,entity,5.174299e+10,NaN,NaN
2,NaN,Others (Not in Reconciliation Scope),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Emporium Fees / Sale Fees,NaN,NaN,1.140164e+10,entity,1.140164e+10,NaN,NaN
3,NaN,Others (Not in Reconciliation Scope),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Supervision Fees,NaN,NaN,1.246891e+09,entity,1.246891e+09,NaN,NaN
4,NaN,Others (Not in Reconciliation Scope),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Other significant payments,NaN,NaN,2.186526e+09,entity,2.186526e+09,NaN,NaN

In [17]:
df_gemsjade['revenue_stream_short'] = df_gemsjade['revenue_stream_short'].replace({'Other significant payments (&gt; 50,000 USD)': 'Other significant payments'})

## Remove negative payments for Sankey

In [18]:
df_gemsjade = df_gemsjade[df_gemsjade["value_reported"] >= 0]

## Prepare Source-Target-Value dataframe

In [19]:
links = pd.DataFrame(columns=['source','target','value','type'])

In [20]:
to_append = df_gemsjade.groupby(['revenue_stream_short'],as_index=False)['type','value_reported','value_reported_as_USD','total_payments'].sum()
to_append["target"] = "Myanmar Gems Enterprise"
to_append.rename(columns = {'revenue_stream_short':'source', 'value_reported' : 'value'}, inplace = True)
to_append = to_append.sort_values(by=['value'], ascending = False)
links = pd.concat([links,to_append])

print(to_append['value'].sum())
links

380196722113.0

,source,target,total_payments,type,value,value_reported_as_USD
3,Sale Split,Myanmar Gems Enterprise,2.381985e+11,NaN,1.859303e+11,139703870.0
2,Royalties,Myanmar Gems Enterprise,3.136187e+11,NaN,1.700241e+11,61354119.0
0,Emporium Fees / Sale Fees,Myanmar Gems Enterprise,2.139276e+11,NaN,1.752952e+10,6379800.0
4,Supervision Fees,Myanmar Gems Enterprise,1.877024e+11,NaN,4.436739e+09,3320985.0
1,Other significant payments,Myanmar Gems Enterprise,4.080459e+09,NaN,2.276081e+09,93237.0

In [21]:
append_dict_transfers = [{'source': 'Myanmar Gems Enterprise', 'type': 'entity',
                       'target': 'State Contribution', 'value': 48367022000 },
                         
                         {'source': 'Myanmar Gems Enterprise', 'type': 'entity', 
                       'target': 'Transfers to Other Accounts', 'value': 195516457782 },
                         
                         {'source': 'Myanmar Gems Enterprise', 'type': 'entity', 
                       'target': 'Commercial Tax', 'value': 21499000 },
                         
                         {'source': 'Myanmar Gems Enterprise', 'type': 'entity', 
                       'target': 'Corporate Income Tax', 'value': 60458777000 },
                         
                         {'source': 'Myanmar Gems Enterprise', 'type': 'entity', 
                       'target': 'Other material transfers', 'value': 119588538585 },
                         
                         {'source': 'State Contribution', 'target_type': 'entity',
                       'target': 'Ministry of Finance', 'value': 48367022000 },
                         
                         {'source': 'Corporate Income Tax', 
                       'target': 'Internal Revenue Department', 'value': 60458777000 },
                         
                         {'source': 'Commercial Tax', 
                       'target': 'Internal Revenue Department', 'value': 21499000 },
                        
                         {'source': 'Internal Revenue Department', 'type': 'entity','target_type': 'entity',
                       'target': 'Ministry of Finance', 'value': 60480276000 }]

append_dict_transfers_df = pd.DataFrame(append_dict_transfers)
links = pd.concat([links, append_dict_transfers_df])
links

,source,target,target_type,total_payments,type,value,value_reported_as_USD
3,Sale Split,Myanmar Gems Enterprise,NaN,2.381985e+11,NaN,1.859303e+11,139703870.0
2,Royalties,Myanmar Gems Enterprise,NaN,3.136187e+11,NaN,1.700241e+11,61354119.0
0,Emporium Fees / Sale Fees,Myanmar Gems Enterprise,NaN,2.139276e+11,NaN,1.752952e+10,6379800.0
4,Supervision Fees,Myanmar Gems Enterprise,NaN,1.877024e+11,NaN,4.436739e+09,3320985.0
1,Other significant payments,Myanmar Gems Enterprise,NaN,4.080459e+09,NaN,2.276081e+09,93237.0
0,Myanmar Gems Enterprise,State Contribution,NaN,NaN,entity,4.836702e+10,NaN
1,Myanmar Gems Enterprise,Transfers to Other Accounts,NaN,NaN,entity,1.955165e+11,NaN
2,Myanmar Gems Enterprise,Commercial Tax,NaN,NaN,entity,2.149900e+07,NaN
3,Myanmar Gems Enterprise,Corporate Income Tax,NaN,NaN,entity,6.045878e+10,NaN
4,Myanmar Gems Enterprise,Other material transfers,NaN,NaN,entity,1.195885e+11,NaN
5,State Contribution,Ministry of Finance,entity,NaN,NaN,4.836702e+10,NaN
6,Corporate Income Tax,Internal Revenue Department,NaN,NaN,NaN,6.045878e+10,NaN
7,Commercial Tax,Internal Revenue Department,NaN,NaN,NaN,2.149900e+07,NaN
8,Internal Revenue Department,Ministry of Finance,entity,NaN,entity,6.048028e+10,NaN

In [22]:
to_append = df_gemsjade.groupby(['revenue_stream_short','Company_name_cl','type'],as_index=False)['value_reported','value_reported_as_USD','total_payments'].sum()
to_append.rename(columns = {'Company_name_cl':'source','revenue_stream_short':'target', 'value_reported' : 'value'}, inplace = True)
to_append = to_append.sort_values(by=['type','total_payments','value'], ascending = False)
links = pd.concat([links,to_append])

print(to_append['value'].sum())
links

380196722113.0

,source,target,target_type,total_payments,type,value,value_reported_as_USD
3,Sale Split,Myanmar Gems Enterprise,NaN,2.381985e+11,NaN,1.859303e+11,139703870.0
2,Royalties,Myanmar Gems Enterprise,NaN,3.136187e+11,NaN,1.700241e+11,61354119.0
0,Emporium Fees / Sale Fees,Myanmar Gems Enterprise,NaN,2.139276e+11,NaN,1.752952e+10,6379800.0
4,Supervision Fees,Myanmar Gems Enterprise,NaN,1.877024e+11,NaN,4.436739e+09,3320985.0
1,Other significant payments,Myanmar Gems Enterprise,NaN,4.080459e+09,NaN,2.276081e+09,93237.0
0,Myanmar Gems Enterprise,State Contribution,NaN,NaN,entity,4.836702e+10,NaN
1,Myanmar Gems Enterprise,Transfers to Other Accounts,NaN,NaN,entity,1.955165e+11,NaN
2,Myanmar Gems Enterprise,Commercial Tax,NaN,NaN,entity,2.149900e+07,NaN
3,Myanmar Gems Enterprise,Corporate Income Tax,NaN,NaN,entity,6.045878e+10,NaN
4,Myanmar Gems Enterprise,Other material transfers,NaN,NaN,entity,1.195885e+11,NaN
5,State Contribution,Ministry of Finance,entity,NaN,NaN,4.836702e+10,NaN
6,Corporate Income Tax,Internal Revenue Department,NaN,NaN,NaN,6.045878e+10,NaN
7,Commercial Tax,Internal Revenue Department,NaN,NaN,NaN,2.149900e+07,NaN
8,Internal Revenue Department,Ministry of Finance,entity,NaN,entity,6.048028e+10,NaN
49,Others (Not in Reconciliation Scope),Royalties,NaN,1.110928e+11,entity,1.110928e+11,NaN
77,Others (Not in Reconciliation Scope),Sale Split,NaN,5.174299e+10,entity,5.174299e+10,NaN
67,GREAT GENESIS GEMS COMPANY LIMITED,Sale Split,NaN,2.001655e+10,entity,1.500496e+10,15621836.0
38,GREAT GENESIS GEMS COMPANY LIMITED,Royalties,NaN,2.001655e+10,entity,4.245309e+09,4419839.0
5,GREAT GENESIS GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,2.001655e+10,entity,3.842051e+08,400000.0
91,GREAT GENESIS GEMS COMPANY LIMITED,Supervision Fees,NaN,2.001655e+10,entity,3.820778e+08,397785.0
84,WAI AUNG GABAR GEMS COMPANY LIMITED,Sale Split,NaN,1.807804e+10,entity,1.339731e+10,13948088.0
57,WAI AUNG GABAR GEMS COMPANY LIMITED,Royalties,NaN,1.807804e+10,entity,3.942465e+09,4104545.0
24,WAI AUNG GABAR GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.807804e+10,entity,4.170156e+08,434160.0
108,WAI AUNG GABAR GEMS COMPANY LIMITED,Supervision Fees,NaN,1.807804e+10,entity,3.212483e+08,334455.0
78,RICHEST GEMS COMPANY LIMITED,Sale Split,NaN,1.604481e+10,entity,1.210528e+10,12602939.0
50,RICHEST GEMS COMPANY LIMITED,Royalties,NaN,1.604481e+10,entity,3.306123e+09,3442042.0
17,RICHEST GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.604481e+10,entity,3.363241e+08,350151.0
102,RICHEST GEMS COMPANY LIMITED,Supervision Fees,NaN,1.604481e+10,entity,2.970860e+08,309300.0
87,YAR ZA HTAR NE GEMS COMPANY LIMITED,Sale Split,NaN,1.279908e+10,entity,1.034887e+10,10774326.0
63,YAR ZA HTAR NE GEMS COMPANY LIMITED,Royalties,NaN,1.279908e+10,entity,1.818793e+09,1893566.0
...,...,...,...,...,...,...,...
11,MYANMAR IMPERIAL JADE (GEMS & JEWELLERY) COMPA...,Emporium Fees / Sale Fees,NaN,4.175896e+09,entity,3.447987e+08,358974.0
59,WINN LEI YADANAR COMPANY LIMITED,Royalties,NaN,2.341319e+09,entity,2.147999e+09,2236306.0
26,WINN LEI YADANAR COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,2.341319e+09,entity,1.933199e+08,201268.0
34,AUNG HEIN MIN GEMS COMPANY LIMITED,Royalties,NaN,2.196766e+09,entity,1.960794e+09,2041405.0
1,AUNG HEIN MIN GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,2.196766e+09,entity,2.016849e+08,209976.0
65,AUNG HEIN MIN GEMS COMPANY LIMITED,Sale Split,NaN,2.196766e+09,entity,3.339024e+07,34763.0
89,AUNG HEIN MIN GEMS COMPANY LIMITED,Supervision Fees,NaN,2.196766e+09,entity,8.961113e+05,933.0
31,Others (Not in Reconciliation Scope),Other significant payments,NaN,2.186526e+09,entity,2.186526e+09,NaN
54,"Shwe Ywet Hlwar Gems Co.,.Ltd.",Royalties,NaN,2.083837e+09,entity,1.812024e+09,1886519.0
21,"Shwe Ywet Hlwar Gems Co.,.Ltd.",Emporium Fees / Sale Fees,NaN,2.083837e+09,entity,1.694213e+08,176386.0
82,"Shwe Ywet Hlwar Gems Co.,.Ltd.",Sale Split,NaN,2.083837e+09,entity,9.859892e+07,102652.0
106,"Shwe Ywet Hlwar Gems Co.,.Ltd.",Supervision Fees,NaN,2.083837e+09,entity,3.792266e+06,3948.0
62,YANDANAR YAUNG CHI GEMS COMPANY LIMITED,Royalties,NaN,1.893933e+09,entity,1.630513e+09,1697545.0
29,YANDANAR YAUNG CHI GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.893933e+09,entity,1.738648e+08,181013.0
32,YANDANAR YAUNG CHI GEMS COMPANY LIMITED,Other significant payments,NaN,1.893933e+09,entity,8.955549e+07,93237.0
75,NATIONAL PROSPERITY GEMS COMPANY LIMITED,Sale Split,NaN,1.453792e+09,entity,1.105682e+09,1151138.0
47,NATIONAL PROSPERITY GEMS COMPANY LIMITED,Royalties,NaN,1.453792e+09,entity,2.894789e+08,301380.0
14,NATIONAL PROSPERITY GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.453792e+09,entity,3.257888e+07,33918.0
99,NATIONAL PROSPERITY GEMS COMPANY LIMITED,Supervision Fees,NaN,1.453792e+09,entity,2.605310e+07,27124.0
101,Others (Not in Reconciliation Scope),Supervision Fees,NaN,1.246891e+09,entity,1.246891e+09,NaN
53,"Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.",Royalties,NaN,1.188666e+09,entity,8.854260e+08,921827.0
81,"Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.",Sale Split,NaN,1.188666e+09,entity,2.119117e+08,220624.0
20,"Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.",Emporium Fees / Sale Fees,NaN,1.188666e+09,entity,8.556557e+07,89083.0
105,"Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.",Supervision Fees,NaN,1.188666e+09,entity,5.763085e+06,6000.0
58,WAI FAMILY GEMS COMPANY LIMITED,Royalties,NaN,1.109455e+09,entity,1.012437e+09,1054060.0
25,WAI FAMILY GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.109455e+09,entity,9.701789e+07,101006.0
36,AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED,Royalties,NaN,1.083479e+09,entity,9.940174e+08,1034883.0
3,AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.083479e+09,entity,8.946155e+07,93139.0
56,TREASURE WHITE LOTUS GEMS COMPANY LIMITED,Royalties,NaN,1.007072e+09,entity,9.234732e+08,961438.0
23,TREASURE WHITE LOTUS GEMS COMPANY LIMITED,Emporium Fees / Sale Fees,NaN,1.007072e+09,entity,8.359920e+07,87036.0

In [23]:
#to_append = df.groupby(['Payment Type','Reporting Company'],as_index=False)['Value (USD)'].sum()
#to_append.rename(columns = {'Payment Type':'source','Reporting Company':'target', 'Value (USD)' : 'value'}, inplace = True)
#to_append = to_append.sort_values(by=['value'], ascending = False)
#links = pd.concat([links,to_append])

#print(to_append['value'].sum())
#links

In [24]:
unique_source = links['source'].unique()
unique_targets = links['target'].unique()

unique_source = pd.merge(pd.DataFrame(unique_source), links, left_on=0, right_on='source', how='left')
unique_source = unique_source.filter([0,'type'])
unique_targets = pd.merge(pd.DataFrame(unique_targets), links, left_on=0, right_on='target', how='left')
unique_targets = unique_targets.filter([0,'target_type'])
unique_targets.rename(columns = {'target_type':'type'}, inplace = True)

unique_list = pd.concat([unique_source[0], unique_targets[0]]).unique()

unique_list = pd.merge(pd.DataFrame(unique_list), \
                       pd.concat([unique_source, unique_targets]), left_on=0, right_on=0, how='left')

unique_list.drop_duplicates(subset=0, keep='first', inplace=True)

replace_dict = {k: v for v, k in enumerate(unique_list[0])}
unique_list
#replace_dict

                                                     0    type
0                                           Sale Split     NaN
25                                           Royalties     NaN
57                           Emporium Fees / Sale Fees     NaN
89                                    Supervision Fees     NaN
114                         Other significant payments     NaN
117                            Myanmar Gems Enterprise  entity
127                                 State Contribution     NaN
129                               Corporate Income Tax     NaN
131                                     Commercial Tax     NaN
133                        Internal Revenue Department  entity
136               Others (Not in Reconciliation Scope)  entity
141                 GREAT GENESIS GEMS COMPANY LIMITED  entity
145                WAI AUNG GABAR GEMS COMPANY LIMITED  entity
149                       RICHEST GEMS COMPANY LIMITED  entity
153                YAR ZA HTAR NE GEMS COMPANY LIMITED  entity
157      THI RAW MANI GEMS & JEWELLERY COMPANY LIMITED  entity
161      Shining Star Light Gems & Jewellery Co., Ltd.  entity
165           KYAUK SEINN NAGAR (GEMS) COMPANY LIMITED  entity
169                       Sein Lom Taung Tan Gems Ltd.  entity
173                      JADE MOUNTAIN COMPANY LIMITED  entity
177           (1.1.1) GEMS & JEWELLERY COMPANY LIMITED  entity
181                                     Myanmar Si Thu  entity
185         LINN LETT WIN YADANAR GEMS COMPANY LIMITED  entity
189            YADANAR TAUNG TANN GEMS COMPANY LIMITED  entity
193                          AYAR JADE COMPANY LIMITED  entity
197                         XIE FAMILY COMPANY LIMITED  entity
201                            Myat Yamon Gems Co.,Ltd  entity
205          KYAING INTERNATIONAL GEMS COMPANY LIMITED  entity
209                  NAY LA PWINT GEMS COMPANY LIMITED  entity
213                         Ever Winner Gems Co., Ltd.  entity
215  KHIN ZAW AUNG & BROTHERS GEMS AND JEWELLERY CO...  entity
219  MYANMAR IMPERIAL JADE (GEMS & JEWELLERY) COMPA...  entity
221                   WINN LEI YADANAR COMPANY LIMITED  entity
223                 AUNG HEIN MIN GEMS COMPANY LIMITED  entity
227                     Shwe Ywet Hlwar Gems Co.,.Ltd.  entity
231            YANDANAR YAUNG CHI GEMS COMPANY LIMITED  entity
234           NATIONAL PROSPERITY GEMS COMPANY LIMITED  entity
238             Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.  entity
242                    WAI FAMILY GEMS COMPANY LIMITED  entity
244    AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED  entity
246          TREASURE WHITE LOTUS GEMS COMPANY LIMITED  entity
248                        Transfers to Other Accounts     NaN
249                           Other material transfers     NaN
250                                Ministry of Finance  entity

In [25]:
links_replaced = links.replace({"source": replace_dict,"target": replace_dict})

In [26]:
links_replaced

,source,target,target_type,total_payments,type,value,value_reported_as_USD
3,0,5,NaN,2.381985e+11,NaN,1.859303e+11,139703870.0
2,1,5,NaN,3.136187e+11,NaN,1.700241e+11,61354119.0
0,2,5,NaN,2.139276e+11,NaN,1.752952e+10,6379800.0
4,3,5,NaN,1.877024e+11,NaN,4.436739e+09,3320985.0
1,4,5,NaN,4.080459e+09,NaN,2.276081e+09,93237.0
0,5,6,NaN,NaN,entity,4.836702e+10,NaN
1,5,41,NaN,NaN,entity,1.955165e+11,NaN
2,5,8,NaN,NaN,entity,2.149900e+07,NaN
3,5,7,NaN,NaN,entity,6.045878e+10,NaN
4,5,42,NaN,NaN,entity,1.195885e+11,NaN
5,6,43,entity,NaN,NaN,4.836702e+10,NaN
6,7,9,NaN,NaN,NaN,6.045878e+10,NaN
7,8,9,NaN,NaN,NaN,2.149900e+07,NaN
8,9,43,entity,NaN,entity,6.048028e+10,NaN
49,10,1,NaN,1.110928e+11,entity,1.110928e+11,NaN
77,10,0,NaN,5.174299e+10,entity,5.174299e+10,NaN
67,11,0,NaN,2.001655e+10,entity,1.500496e+10,15621836.0
38,11,1,NaN,2.001655e+10,entity,4.245309e+09,4419839.0
5,11,2,NaN,2.001655e+10,entity,3.842051e+08,400000.0
91,11,3,NaN,2.001655e+10,entity,3.820778e+08,397785.0
84,12,0,NaN,1.807804e+10,entity,1.339731e+10,13948088.0
57,12,1,NaN,1.807804e+10,entity,3.942465e+09,4104545.0
24,12,2,NaN,1.807804e+10,entity,4.170156e+08,434160.0
108,12,3,NaN,1.807804e+10,entity,3.212483e+08,334455.0
78,13,0,NaN,1.604481e+10,entity,1.210528e+10,12602939.0
50,13,1,NaN,1.604481e+10,entity,3.306123e+09,3442042.0
17,13,2,NaN,1.604481e+10,entity,3.363241e+08,350151.0
102,13,3,NaN,1.604481e+10,entity,2.970860e+08,309300.0
87,14,0,NaN,1.279908e+10,entity,1.034887e+10,10774326.0
63,14,1,NaN,1.279908e+10,entity,1.818793e+09,1893566.0
...,...,...,...,...,...,...,...
11,31,2,NaN,4.175896e+09,entity,3.447987e+08,358974.0
59,32,1,NaN,2.341319e+09,entity,2.147999e+09,2236306.0
26,32,2,NaN,2.341319e+09,entity,1.933199e+08,201268.0
34,33,1,NaN,2.196766e+09,entity,1.960794e+09,2041405.0
1,33,2,NaN,2.196766e+09,entity,2.016849e+08,209976.0
65,33,0,NaN,2.196766e+09,entity,3.339024e+07,34763.0
89,33,3,NaN,2.196766e+09,entity,8.961113e+05,933.0
31,10,4,NaN,2.186526e+09,entity,2.186526e+09,NaN
54,34,1,NaN,2.083837e+09,entity,1.812024e+09,1886519.0
21,34,2,NaN,2.083837e+09,entity,1.694213e+08,176386.0
82,34,0,NaN,2.083837e+09,entity,9.859892e+07,102652.0
106,34,3,NaN,2.083837e+09,entity,3.792266e+06,3948.0
62,35,1,NaN,1.893933e+09,entity,1.630513e+09,1697545.0
29,35,2,NaN,1.893933e+09,entity,1.738648e+08,181013.0
32,35,4,NaN,1.893933e+09,entity,8.955549e+07,93237.0
75,36,0,NaN,1.453792e+09,entity,1.105682e+09,1151138.0
47,36,1,NaN,1.453792e+09,entity,2.894789e+08,301380.0
14,36,2,NaN,1.453792e+09,entity,3.257888e+07,33918.0
99,36,3,NaN,1.453792e+09,entity,2.605310e+07,27124.0
101,10,3,NaN,1.246891e+09,entity,1.246891e+09,NaN
53,37,1,NaN,1.188666e+09,entity,8.854260e+08,921827.0
81,37,0,NaN,1.188666e+09,entity,2.119117e+08,220624.0
20,37,2,NaN,1.188666e+09,entity,8.556557e+07,89083.0
105,37,3,NaN,1.188666e+09,entity,5.763085e+06,6000.0
58,38,1,NaN,1.109455e+09,entity,1.012437e+09,1054060.0
25,38,2,NaN,1.109455e+09,entity,9.701789e+07,101006.0
36,39,1,NaN,1.083479e+09,entity,9.940174e+08,1034883.0
3,39,2,NaN,1.083479e+09,entity,8.946155e+07,93139.0
56,40,1,NaN,1.007072e+09,entity,9.234732e+08,961438.0
23,40,2,NaN,1.007072e+09,entity,8.359920e+07,87036.0

In [27]:
nodes = pd.DataFrame(unique_list)
nodes.rename(columns = {0:'name'}, inplace = True)

In [28]:
nodes_json= pd.DataFrame(nodes).to_json(orient='records')
nodes_json

'[{"name":"Sale Split","type":null},{"name":"Royalties","type":null},{"name":"Emporium Fees \\/ Sale Fees","type":null},{"name":"Supervision Fees","type":null},{"name":"Other significant payments","type":null},{"name":"Myanmar Gems Enterprise","type":"entity"},{"name":"State Contribution","type":null},{"name":"Corporate Income Tax","type":null},{"name":"Commercial Tax","type":null},{"name":"Internal Revenue Department","type":"entity"},{"name":"Others (Not in Reconciliation Scope)","type":"entity"},{"name":"GREAT GENESIS GEMS COMPANY LIMITED","type":"entity"},{"name":"WAI AUNG GABAR GEMS COMPANY LIMITED","type":"entity"},{"name":"RICHEST GEMS COMPANY LIMITED","type":"entity"},{"name":"YAR ZA HTAR NE GEMS COMPANY LIMITED","type":"entity"},{"name":"THI RAW MANI GEMS & JEWELLERY COMPANY LIMITED","type":"entity"},{"name":"Shining Star Light Gems & Jewellery Co., Ltd.","type":"entity"},{"name":"KYAUK SEINN NAGAR (GEMS) COMPANY LIMITED","type":"entity"},{"name":"Sein Lom Taung Tan Gems Ltd.","type":"entity"},{"name":"JADE MOUNTAIN COMPANY LIMITED","type":"entity"},{"name":"(1.1.1) GEMS & JEWELLERY COMPANY LIMITED","type":"entity"},{"name":"Myanmar Si Thu","type":"entity"},{"name":"LINN LETT WIN YADANAR GEMS COMPANY LIMITED","type":"entity"},{"name":"YADANAR TAUNG TANN GEMS COMPANY LIMITED","type":"entity"},{"name":"AYAR JADE COMPANY LIMITED","type":"entity"},{"name":"XIE FAMILY COMPANY LIMITED","type":"entity"},{"name":"Myat Yamon Gems Co.,Ltd","type":"entity"},{"name":"KYAING INTERNATIONAL GEMS COMPANY LIMITED","type":"entity"},{"name":"NAY LA PWINT GEMS COMPANY LIMITED","type":"entity"},{"name":"Ever Winner Gems Co., Ltd.","type":"entity"},{"name":"KHIN ZAW AUNG & BROTHERS GEMS AND JEWELLERY COMPANY LIMITED","type":"entity"},{"name":"MYANMAR IMPERIAL JADE (GEMS & JEWELLERY) COMPANY LIMITED","type":"entity"},{"name":"WINN LEI YADANAR COMPANY LIMITED","type":"entity"},{"name":"AUNG HEIN MIN GEMS COMPANY LIMITED","type":"entity"},{"name":"Shwe Ywet Hlwar Gems Co.,.Ltd.","type":"entity"},{"name":"YANDANAR YAUNG CHI GEMS COMPANY LIMITED","type":"entity"},{"name":"NATIONAL PROSPERITY GEMS COMPANY LIMITED","type":"entity"},{"name":"Shwe Wah Myay (Mandalay)Gems& Co.,Ltd.","type":"entity"},{"name":"WAI FAMILY GEMS COMPANY LIMITED","type":"entity"},{"name":"AYEYAR YADANAR GEMS & JEWELLERY COMPANY LIMITED","type":"entity"},{"name":"TREASURE WHITE LOTUS GEMS COMPANY LIMITED","type":"entity"},{"name":"Transfers to Other Accounts","type":null},{"name":"Other material transfers","type":null},{"name":"Ministry of Finance","type":"entity"}]'

In [29]:
links_json= pd.DataFrame(links_replaced).to_json(orient='records')
links_json

'[{"source":0,"target":5,"target_type":null,"total_payments":238198542926.6718139648,"type":null,"value":185930251282.5733642578,"value_reported_as_USD":139703870.0},{"source":1,"target":5,"target_type":null,"total_payments":313618666344.5166015625,"type":null,"value":170024130471.1452636719,"value_reported_as_USD":61354119.0},{"source":2,"target":5,"target_type":null,"total_payments":213927554410.5165710449,"type":null,"value":17529519654.9551620483,"value_reported_as_USD":6379800.0},{"source":3,"target":5,"target_type":null,"total_payments":187702438814.6718139648,"type":null,"value":4436739393.4279022217,"value_reported_as_USD":3320985.0},{"source":4,"target":5,"target_type":null,"total_payments":4080458833.2069458961,"type":null,"value":2276081310.4148459435,"value_reported_as_USD":93237.0},{"source":5,"target":6,"target_type":null,"total_payments":null,"type":"entity","value":48367022000.0,"value_reported_as_USD":null},{"source":5,"target":41,"target_type":null,"total_payments":null,"type":"entity","value":195516457782.0,"value_reported_as_USD":null},{"source":5,"target":8,"target_type":null,"total_payments":null,"type":"entity","value":21499000.0,"value_reported_as_USD":null},{"source":5,"target":7,"target_type":null,"total_payments":null,"type":"entity","value":60458777000.0,"value_reported_as_USD":null},{"source":5,"target":42,"target_type":null,"total_payments":null,"type":"entity","value":119588538585.0,"value_reported_as_USD":null},{"source":6,"target":43,"target_type":"entity","total_payments":null,"type":null,"value":48367022000.0,"value_reported_as_USD":null},{"source":7,"target":9,"target_type":null,"total_payments":null,"type":null,"value":60458777000.0,"value_reported_as_USD":null},{"source":8,"target":9,"target_type":null,"total_payments":null,"type":null,"value":21499000.0,"value_reported_as_USD":null},{"source":9,"target":43,"target_type":"entity","total_payments":null,"type":"entity","value":60480276000.0,"value_reported_as_USD":null},{"source":10,"target":1,"target_type":null,"total_payments":111092756522.0,"type":"entity","value":111092756522.0,"value_reported_as_USD":null},{"source":10,"target":0,"target_type":null,"total_payments":51742994736.0,"type":"entity","value":51742994736.0,"value_reported_as_USD":null},{"source":11,"target":0,"target_type":null,"total_payments":20016553974.3760375977,"type":"entity","value":15004962403.7789993286,"value_reported_as_USD":15621836.0},{"source":11,"target":1,"target_type":null,"total_payments":20016553974.3760375977,"type":"entity","value":4245308740.3607001305,"value_reported_as_USD":4419839.0},{"source":11,"target":2,"target_type":null,"total_payments":20016553974.3760375977,"type":"entity","value":384205066.7981700301,"value_reported_as_USD":400000.0},{"source":11,"target":3,"target_type":null,"total_payments":20016553974.3760375977,"type":"entity","value":382077763.4381700158,"value_reported_as_USD":397785.0},{"source":12,"target":0,"target_type":null,"total_payments":18078036756.103313446,"type":"entity","value":13397307541.9280014038,"value_reported_as_USD":13948088.0},{"source":12,"target":1,"target_type":null,"total_payments":18078036756.103313446,"type":"entity","value":3942465305.63560009,"value_reported_as_USD":4104545.0},{"source":12,"target":2,"target_type":null,"total_payments":18078036756.103313446,"type":"entity","value":417015613.1557700038,"value_reported_as_USD":434160.0},{"source":12,"target":3,"target_type":null,"total_payments":18078036756.103313446,"type":"entity","value":321248295.3839399815,"value_reported_as_USD":334455.0},{"source":13,"target":0,"target_type":null,"total_payments":16044808582.2006378174,"type":"entity","value":12105275122.6339988708,"value_reported_as_USD":12602939.0},{"source":13,"target":1,"target_type":null,"total_payments":16044808582.2006378174,"type":"entity","value":3306123319.1367998123,"value_reported_as_USD":3442042.0},{"source":13,"target":2,"target_type":null,"total_payments":16044808582.2006378174,"type":"entity","value":336324094.9094499946,"value_reported_as_USD":350151.0},{"source":13,"target":3,"target_type":null,"total_payments":16044808582.2006378174,"type":"entity","value":297086045.5203899741,"value_reported_as_USD":309300.0},{"source":14,"target":0,"target_type":null,"total_payments":12799079994.6889801025,"type":"entity","value":10348870278.4599990845,"value_reported_as_USD":10774326.0},{"source":14,"target":1,"target_type":null,"total_payments":12799079994.6889801025,"type":"entity","value":1818793350.5064001083,"value_reported_as_USD":1893566.0},{"source":14,"target":2,"target_type":null,"total_payments":12799079994.6889801025,"type":"entity","value":467724960.3112900257,"value_reported_as_USD":486954.0},{"source":14,"target":3,"target_type":null,"total_payments":12799079994.6889801025,"type":"entity","value":163691405.4112899899,"value_reported_as_USD":170421.0},{"source":15,"target":0,"target_type":null,"total_payments":11581352072.6722202301,"type":"entity","value":8613593872.3738002777,"value_reported_as_USD":8967710.0},{"source":15,"target":1,"target_type":null,"total_payments":11581352072.6722202301,"type":"entity","value":2519338543.0778999329,"value_reported_as_USD":2622912.0},{"source":15,"target":2,"target_type":null,"total_payments":11581352072.6722202301,"type":"entity","value":229642694.5012899935,"value_reported_as_USD":239084.0},{"source":15,"target":3,"target_type":null,"total_payments":11581352072.6722202301,"type":"entity","value":218776962.7192299962,"value_reported_as_USD":227771.0},{"source":10,"target":2,"target_type":null,"total_payments":11401644588.0,"type":"entity","value":11401644588.0,"value_reported_as_USD":null},{"source":16,"target":0,"target_type":null,"total_payments":9559134910.6866607666,"type":"entity","value":5749173952.8357000351,"value_reported_as_USD":5985530.0},{"source":16,"target":1,"target_type":null,"total_payments":9559134910.6866607666,"type":"entity","value":3355461821.583799839,"value_reported_as_USD":3493409.0},{"source":16,"target":2,"target_type":null,"total_payments":9559134910.6866607666,"type":"entity","value":309726731.5611100197,"value_reported_as_USD":322460.0},{"source":16,"target":3,"target_type":null,"total_payments":9559134910.6866607666,"type":"entity","value":144772404.7060500085,"value_reported_as_USD":150724.0},{"source":17,"target":0,"target_type":null,"total_payments":9122210196.6229801178,"type":"entity","value":6952791229.9081001282,"value_reported_as_USD":7238630.0},{"source":17,"target":1,"target_type":null,"total_payments":9122210196.6229801178,"type":"entity","value":1789227334.1271998882,"value_reported_as_USD":1862785.0},{"source":17,"target":2,"target_type":null,"total_payments":9122210196.6229801178,"type":"entity","value":223403323.9985899925,"value_reported_as_USD":232588.0},{"source":17,"target":3,"target_type":null,"total_payments":9122210196.6229801178,"type":"entity","value":156788308.5890899897,"value_reported_as_USD":163234.0},{"source":18,"target":0,"target_type":null,"total_payments":8686355363.6937999725,"type":"entity","value":6679489706.5233001709,"value_reported_as_USD":6954092.0},{"source":18,"target":1,"target_type":null,"total_payments":8686355363.6937999725,"type":"entity","value":1642838648.3612000942,"value_reported_as_USD":1710378.0},{"source":18,"target":2,"target_type":null,"total_payments":8686355363.6937999725,"type":"entity","value":216171554.9396499991,"value_reported_as_USD":225059.0},{"source":18,"target":3,"target_type":null,"total_payments":8686355363.6937999725,"type":"entity","value":147855453.8696500063,"value_reported_as_USD":153934.0},{"source":19,"target":0,"target_type":null,"total_payments":8592584112.4872398376,"type":"entity","value":6416195690.9054002762,"value_reported_as_USD":6679974.0},{"source":19,"target":1,"target_type":null,"total_payments":8592584112.4872398376,"type":"entity","value":1816162216.269299984,"value_reported_as_USD":1890827.0},{"source":19,"target":2,"target_type":null,"total_payments":8592584112.4872398376,"type":"entity","value":210626296.1713699996,"value_reported_as_USD":219285.0},{"source":19,"target":3,"target_type":null,"total_payments":8592584112.4872398376,"type":"entity","value":149599909.1411699951,"value_reported_as_USD":155750.0},{"source":20,"target":0,"target_type":null,"total_payments":8420017500.6984491348,"type":"entity","value":6067505197.6282997131,"value_reported_as_USD":6316948.0},{"source":20,"target":1,"target_type":null,"total_payments":8420017500.6984491348,"type":"entity","value":1985585020.3972001076,"value_reported_as_USD":2067215.0},{"source":20,"target":2,"target_type":null,"total_payments":8420017500.6984491348,"type":"entity","value":221349533.6371700168,"value_reported_as_USD":230450.0},{"source":20,"target":3,"target_type":null,"total_payments":8420017500.6984491348,"type":"entity","value":145577749.0357800126,"value_reported_as_USD":151563.0},{"source":21,"target":0,"target_type":null,"total_payments":8142193295.9828195572,"type":"entity","value":6129155548.2059001923,"value_reported_as_USD":6381133.0},{"source":21,"target":1,"target_type":null,"total_payments":8142193295.9828195572,"type":"entity","value":1696545537.2020001411,"value_reported_as_USD":1766293.0},{"source":21,"target":2,"target_type":null,"total_payments":8142193295.9828195572,"type":"entity","value":163803170.2124600112,"value_reported_as_USD":170537.0},{"source":21,"target":3,"target_type":null,"total_payments":8142193295.9828195572,"type":"entity","value":152689040.3624600172,"value_reported_as_USD":158966.0},{"source":22,"target":0,"target_type":null,"total_payments":8079840827.2544708252,"type":"entity","value":5723627073.9181003571,"value_reported_as_USD":5958933.0},{"source":22,"target":1,"target_type":null,"total_payments":8079840827.2544708252,"type":"entity","value":2017969271.6017999649,"value_reported_as_USD":2100931.0},{"source":22,"target":2,"target_type":null,"total_payments":8079840827.2544708252,"type":"entity","value":195785346.4370200038,"value_reported_as_USD":203834.0},{"source":22,"target":3,"target_type":null,"total_payments":8079840827.2544708252,"type":"entity","value":142459135.2975499928,"value_reported_as_USD":148316.0},{"source":23,"target":0,"target_type":null,"total_payments":7136626292.6237201691,"type":"entity","value":5347922221.6293001175,"value_reported_as_USD":5567782.0},{"source":23,"target":1,"target_type":null,"total_payments":7136626292.6237201691,"type":"entity","value":1515850953.4867999554,"value_reported_as_USD":1578170.0},{"source":23,"target":2,"target_type":null,"total_payments":7136626292.6237201691,"type":"entity","value":136426558.7538100183,"value_reported_as_USD":142035.0},{"source":23,"target":3,"target_type":null,"total_payments":7136626292.6237201691,"type":"entity","value":136426558.7538100183,"value_reported_as_USD":142035.0},{"source":24,"target":0,"target_type":null,"total_payments":7016874202.7804107666,"type":"entity","value":5089835397.8985004425,"value_reported_as_USD":5299085.0},{"source":24,"target":1,"target_type":null,"total_payments":7016874202.7804107666,"type":"entity","value":1625061386.4732000828,"value_reported_as_USD":1691870.0},{"source":24,"target":2,"target_type":null,"total_payments":7016874202.7804107666,"type":"entity","value":184877268.0254399776,"value_reported_as_USD":192478.0},{"source":24,"target":3,"target_type":null,"total_payments":7016874202.7804107666,"type":"entity","value":117100150.3832699955,"value_reported_as_USD":121914.0},{"source":25,"target":0,"target_type":null,"total_payments":6365314567.7022399902,"type":"entity","value":4769929860.1324996948,"value_reported_as_USD":4966028.0},{"source":25,"target":1,"target_type":null,"total_payments":6365314567.7022399902,"type":"entity","value":1352020936.4344000816,"value_reported_as_USD":1407604.0},{"source":25,"target":2,"target_type":null,"total_payments":6365314567.7022399902,"type":"entity","value":121681885.5676699877,"value_reported_as_USD":126684.0},{"source":25,"target":3,"target_type":null,"total_payments":6365314567.7022399902,"type":"entity","value":121681885.5676699877,"value_reported_as_USD":126684.0},{"source":26,"target":0,"target_type":null,"total_payments":5778485669.2908000946,"type":"entity","value":4043300771.4123001099,"value_reported_as_USD":4209526.0},{"source":26,"target":1,"target_type":null,"total_payments":5778485669.2908000946,"type":"entity","value":1491358687.5648999214,"value_reported_as_USD":1552670.0},{"source":26,"target":2,"target_type":null,"total_payments":5778485669.2908000946,"type":"entity","value":143341842.0851199925,"value_reported_as_USD":149235.0},{"source":26,"target":3,"target_type":null,"total_payments":5778485669.2908000946,"type":"entity","value":100484368.2284800112,"value_reported_as_USD":104615.0},{"source":27,"target":0,"target_type":null,"total_payments":5351261589.4408893585,"type":"entity","value":4041883202.7750000954,"value_reported_as_USD":4208050.0},{"source":27,"target":1,"target_type":null,"total_payments":5351261589.4408893585,"type":"entity","value":1097957021.8203001022,"value_reported_as_USD":1143095.0},{"source":27,"target":2,"target_type":null,"total_payments":5351261589.4408893585,"type":"entity","value":111851560.2709700018,"value_reported_as_USD":116450.0},{"source":27,"target":3,"target_type":null,"total_payments":5351261589.4408893585,"type":"entity","value":99569804.5746180117,"value_reported_as_USD":103663.0},{"source":28,"target":0,"target_type":null,"total_payments":4575571495.6999378204,"type":"entity","value":3070954618.1971998215,"value_reported_as_USD":3197206.0},{"source":28,"target":1,"target_type":null,"total_payments":4575571495.6999378204,"type":"entity","value":1306379345.7490999699,"value_reported_as_USD":1360086.0},{"source":28,"target":2,"target_type":null,"total_payments":4575571495.6999378204,"type":"entity","value":117574086.9974100143,"value_reported_as_USD":122408.0},{"source":28,"target":3,"target_type":null,"total_payments":4575571495.6999378204,"type":"entity","value":80663444.7562279999,"value_reported_as_USD":83980.0},{"source":29,"target":1,"target_type":null,"total_payments":4459206845.4304103851,"type":"entity","value":4088604266.2362999916,"value_reported_as_USD":4256692.0},{"source":29,"target":2,"target_type":null,"total_payments":4459206845.4304103851,"type":"entity","value":370602579.1941100359,"value_reported_as_USD":385839.0},{"source":30,"target":0,"target_type":null,"total_payments":4186185573.7714338303,"type":"entity","value":3185900388.0584998131,"value_reported_as_USD":3316877.0},{"source":30,"target":1,"target_type":null,"total_payments":4186185573.7714338303,"type":"entity","value":831061511.7639900446,"value_reported_as_USD":865228.0},{"source":30,"target":2,"target_type":null,"total_payments":4186185573.7714338303,"type":"entity","value":94428152.0644719899,"value_reported_as_USD":98310.0},{"source":30,"target":3,"target_type":null,"total_payments":4186185573.7714338303,"type":"entity","value":74795521.8844719976,"value_reported_as_USD":77870.0},{"source":31,"target":1,"target_type":null,"total_payments":4175896135.904250145,"type":"entity","value":3831097417.3119001389,"value_reported_as_USD":3988599.0},{"source":31,"target":2,"target_type":null,"total_payments":4175896135.904250145,"type":"entity","value":344798718.5923500061,"value_reported_as_USD":358974.0},{"source":32,"target":1,"target_type":null,"total_payments":2341319304.489470005,"type":"entity","value":2147999412.7505002022,"value_reported_as_USD":2236306.0},{"source":32,"target":2,"target_type":null,"total_payments":2341319304.489470005,"type":"entity","value":193319891.7389699817,"value_reported_as_USD":201268.0},{"source":33,"target":1,"target_type":null,"total_payments":2196765561.4209194183,"type":"entity","value":1960794321.3055000305,"value_reported_as_USD":2041405.0},{"source":33,"target":2,"target_type":null,"total_payments":2196765561.4209194183,"type":"entity","value":201684884.8960700035,"value_reported_as_USD":209976.0},{"source":33,"target":0,"target_type":null,"total_payments":2196765561.4209194183,"type":"entity","value":33390243.9100080021,"value_reported_as_USD":34763.0},{"source":33,"target":3,"target_type":null,"total_payments":2196765561.4209194183,"type":"entity","value":896111.30934147,"value_reported_as_USD":933.0},{"source":10,"target":4,"target_type":null,"total_payments":2186525820.0,"type":"entity","value":2186525820.0,"value_reported_as_USD":null},{"source":34,"target":1,"target_type":null,"total_payments":2083836865.0502045155,"type":"entity","value":1812024355.3248999119,"value_reported_as_USD":1886519.0},{"source":34,"target":2,"target_type":null,"total_payments":2083836865.0502045155,"type":"entity","value":169421326.2106699944,"value_reported_as_USD":176386.0},{"source":34,"target":0,"target_type":null,"total_payments":2083836865.0502045155,"type":"entity","value":98598917.4585369974,"value_reported_as_USD":102652.0},{"source":34,"target":3,"target_type":null,"total_payments":2083836865.0502045155,"type":"entity","value":3792266.0560975997,"value_reported_as_USD":3948.0},{"source":35,"target":1,"target_type":null,"total_payments":1893933013.2069458961,"type":"entity","value":1630512688.3931000233,"value_reported_as_USD":1697545.0},{"source":35,"target":2,"target_type":null,"total_payments":1893933013.2069458961,"type":"entity","value":173864834.3990000188,"value_reported_as_USD":181013.0},{"source":35,"target":4,"target_type":null,"total_payments":1893933013.2069458961,"type":"entity","value":89555490.4148460031,"value_reported_as_USD":93237.0},{"source":36,"target":0,"target_type":null,"total_payments":1453792479.1834058762,"type":"entity","value":1105681613.5950000286,"value_reported_as_USD":1151138.0},{"source":36,"target":1,"target_type":null,"total_payments":1453792479.1834058762,"type":"entity","value":289478886.0918700099,"value_reported_as_USD":301380.0},{"source":36,"target":2,"target_type":null,"total_payments":1453792479.1834058762,"type":"entity","value":32578879.7482680008,"value_reported_as_USD":33918.0},{"source":36,"target":3,"target_type":null,"total_payments":1453792479.1834058762,"type":"entity","value":26053099.7482680008,"value_reported_as_USD":27124.0},{"source":10,"target":3,"target_type":null,"total_payments":1246890624.0,"type":"entity","value":1246890624.0,"value_reported_as_USD":null},{"source":37,"target":1,"target_type":null,"total_payments":1188666306.2402019501,"type":"entity","value":885425958.664069891,"value_reported_as_USD":921827.0},{"source":37,"target":0,"target_type":null,"total_payments":1188666306.2402019501,"type":"entity","value":211911692.406919986,"value_reported_as_USD":220624.0},{"source":37,"target":2,"target_type":null,"total_payments":1188666306.2402019501,"type":"entity","value":85565570.4783339947,"value_reported_as_USD":89083.0},{"source":37,"target":3,"target_type":null,"total_payments":1188666306.2402019501,"type":"entity","value":5763084.6908780998,"value_reported_as_USD":6000.0},{"source":38,"target":1,"target_type":null,"total_payments":1109454992.0279278755,"type":"entity","value":1012437105.5406999588,"value_reported_as_USD":1054060.0},{"source":38,"target":2,"target_type":null,"total_payments":1109454992.0279278755,"type":"entity","value":97017886.4872280061,"value_reported_as_USD":101006.0},{"source":39,"target":1,"target_type":null,"total_payments":1083478915.4296460152,"type":"entity","value":994017361.880409956,"value_reported_as_USD":1034883.0},{"source":39,"target":2,"target_type":null,"total_payments":1083478915.4296460152,"type":"entity","value":89461553.5492359996,"value_reported_as_USD":93139.0},{"source":40,"target":1,"target_type":null,"total_payments":1007072425.3561109304,"type":"entity","value":923473224.0934199095,"value_reported_as_USD":961438.0},{"source":40,"target":2,"target_type":null,"total_payments":1007072425.3561109304,"type":"entity","value":83599201.2626910061,"value_reported_as_USD":87036.0}]'

In [30]:
data = { 'links' : json.loads(links_json), 'nodes' : json.loads(nodes_json) }
data_json = json.dumps(data)
data_json = data_json.replace("\\","")
#print(data_json)
#with open('sankey_data.json', 'w') as outfile:
#    json.dump(data_json, outfile)

text_file = open("sankey_data_2013-14.json", "w")
text_file.write(data_json)
text_file.close()